### ISSUE TITLE
Demo - for line 5 and line 6 from algo

### ISSUE THREAD

**Issue by PinkalShah** [declare-lab/RelationPrompt#6]
Hello, Thanks a ton for the help.
I was wondering where we are suppose to pass the input data(in the form of "context: s") while predict for an complete unseen sentence.

**Comment by chiayewken** [comment]
Hi, for inference of the relation extractor model, you can pass in the path of the data in a json file, based on the [code demo](https://colab.research.google.com/drive/18lrKD30kxEUolQ61o5nzUJM0rvWgpbFK?usp=sharing) and image below. The data file should follow the same format as the [existing data](https://github.com/declare-lab/RelationPrompt/releases/download/v1.0.0/zero_rte_data.zip) .
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/29782952/182578947-ca5d732f-5ef9-4da1-8dce-440b705e7966.png">

**Comment by SaeedNajafi** [comment]
Hi,
What is the exact code to only predict the relation labels assuming the head and tail are fixed?
