### ISSUE TITLE
Bug in Data Splitting on FewRel Dataset

### ISSUE THREAD

**Issue by SaeedNajafi** [declare-lab/RelationPrompt#9]
Hey,
The fewrel dataset has 700 sentences per relation id.

After splitting the FewRel into train/dev/test, you should get 10500 sentences in the test split as you have 15 unseen relation ids.

Using your code, we get fewer sentences on the splits. I tested with seed 12321, and there are 200 sentences missing on the test split.

Please fix this issue and re-evaluate the results for the main paper.

**Comment by chiayewken** [comment]
Hi, the reason for fewer samples is that some samples have the same text, hence they are merged to form the multi-triplet sentences.
